### ISSUE TITLE
JSONP support for crossdomain requests

### ISSUE THREAD

**Issue by klickagent** [xquery/rxq#29]
To create a crossdomain working rest service i need jsonp support. Is there any way to achieve this in current version of restxq? (i am working with exist-db).

**Comment by xquery** [comment]
rxq is written for MarkLogic platform ... you will have to ask on exist-db list.

usually the answer to cross domain support is using a proxy, CORS or some kind of 2-3 tier architecture like https://github.com/marklogic/marklogic-samplestack
