### ISSUE TITLE
Execution of code in Sub database not getting desired results

### ISSUE THREAD

**Issue by sri-prasanna** [xquery/rxq#36]
I have a module that executes a basic 'search:search' function.I have annotated it with RXQ like below:

`%rxq:GET`
`%rxq:path('/v1/search/(.*)')`
`%rxq:produces('application/xml; charset=utf-8')`
`function modx:search($searchTerm) as item()*
{
    return search:search($searchTerm)
};`

When I make this module part of a HTTP application which is attached to a database named databaseA, and invoke the REST endpoint, I get the required result.

But, when I make this module part of a HTTP application which is attached to a database named databaseX, which has databaseA as its sub-database, and invoke the REST endpoint, I get the no result.databaseX has no forest attached to it. So, I am hoping to get all data out of databaseA.

I get the same behaviour by using the same HTTP application, and changing the database from databaseA to databaseX.

If I change the module to be a main module and execute it directly from the browser, I get the desired result.

What could be wrong? The code and config are very basic. Still I am unable to get the desired result. What am I missing? thanks..

**Comment by xquery** [comment]
interesting bug and maybe a bug in the server itself. 

you should be able to work around this by creating a function that executes search:search with an xdmp:eval then call that function.

```
declare function ex1:search_impl($searchTerm){
    xdmp:eval('
import module namespace search = "http://marklogic.com/appservices/search"
     at "/MarkLogic/appservices/search/search.xqy";

    search:search("' || $searchTerm || '")')
};

declare
%rxq:GET
%rxq:path('/v1/mysearch/(.*)')
%rxq:produces('application/xml; charset=utf-8')
function ex1:search($searchTerm) as item()*
{
    ex1:search_impl($searchTerm)
};
```

please do tell me if this works for you  (and your ML version, OS, etc).

**Comment by sri-prasanna** [comment]
Thanks. This does work. I will keep an eye on how complicated this gets, when we introduce more features.

We use version 7.0.1 on Windows 2K8 R2 servers.

**Comment by sri-prasanna** [comment]
I am not a big fan of xdmp:eval.. So, will try other options like xdmp:apply and feedback

**Comment by sri-prasanna** [comment]
xdmp:apply also does not return expected results. So, I will stick to xdmp:eval. thanks.

**Comment by xquery** [comment]
I agree with you that  xdmp:eval is not the 'right answer' - once I have a free moment will track down where the context is being lost.

FWIW- If you are running 7.0-1 I would highly recommend upgrading to 7.0-6.2 but in this case it will not fix this issue as I have verified behavior on latest MarkLogic.

**Comment by xquery** [comment]
using latest MarkLogic server probably fixes this, closing
