### ISSUE TITLE
rxq library layout / structure makes it difficult to import

### ISSUE THREAD

**Issue by jmeekhof** [xquery/rxq#38]
The current directory structure and layout of RXQ doesn't support direct submodule style importing into existing projects.

Currently it's necesary to clone the repository, and then copy and paste into a new project. If the root of the RXQ project was where src/xquery is now, it'd be much easier to directly add rxq to a project as a submodule.

**Comment by xquery** [comment]
thats a good idea - I am currently reconsidering an RXQ2 which would be a rewrite of RXQ
