### ISSUE TITLE
Broken link in the documentation.

### ISSUE THREAD

**Issue by sanjuthomas** [xquery/rxq#41]
Please see the link below in README, the link is broken.

Please review the src/example-simple/rxq-rewriter.xqy to see how to setup your own.

**Comment by xquery** [comment]
links work for me

**Comment by sanjuthomas** [comment]
![image](https://cloud.githubusercontent.com/assets/949540/23276128/28b418d8-f9d7-11e6-8a77-5c85848eccf5.png)

**Comment by RobertSzkutak** [comment]
The links are broken in these two sections of the README (copy and pasted here):

The routing 'magic' is taken care of by [src/xquery/rxq-rewriter.xqy](https://github.com/xquery/rxq/blob/master/src/xquery/rxq-rewriter.xqy) (which you attach to MarkLogic appserver). The `%rxq:GET` annotation specifies the HTTP method and the `%rxq:path` annotation value specifies the concrete URL.

Please review the [src/example-simple/rxq-rewriter.xqy](https://github.com/xquery/rxq/blob/master/src/example-site/rxq-rewriter.xqy) to see how to setup your own.

**Comment by xquery** [comment]
thx for catching that, fixed in develop and now master
