### ISSUE TITLE
rxq.xqy does not specify option mapping.

### ISSUE THREAD

**Issue by heelix** [xquery/rxq#42]
Our codebase uses Sonar for scanning for our xquery code.  One of the things we check for is option mapping - usually expecting folks to turn it off unless they have a darn good reason.  The current code does not specify one way or another, so default behavior is setting it to true.  This an oversight or is rxq use that functionality?

Hoping to add this one liner - officially - or know for sure we need it set to true.

**declare option xdmp:mapping "false";**

**Comment by xquery** [comment]
sounds like a good idea to me ... I have been slowly building RXQ2 ... will include it there.

**Comment by heelix** [comment]
Any chance to update this version?  It is easy for us to pull in minor changes, but RXQ2 would be considered a swapping of frameworks (and a bunch of red tape) - not impossible, but months of work for every project owner to actually get aligned on the build process.

**Comment by xquery** [comment]
master branch has this already ... I created a new release 1.0.1 which includes this
