### ISSUE TITLE
guard rail doc

### ISSUE THREAD

**Issue by xquery** [xquery/rxq#46]

**Comment by damonfeldman** [comment]
My notes on such a doc:
- overall: let people know what is possible/impossible so they don't get 3 days in and have to back out of rxq use
  - in particular, use a different port for native rewriter and ML product rest extensions
  - any other things to know going in

**Comment by xquery** [comment]
ok I do not think we need an additional doc - I will fold this and #47 into a new section into the README

**Comment by xquery** [comment]
I have added a simple bullet to the FAQ

https://github.com/xquery/rxq/wiki/FAQ

can't think of much more to add.
