### ISSUE TITLE
Document when and why someone would use rxq vs the MarkLogic REST API

### ISSUE THREAD

**Issue by dmcassel** [xquery/rxq#47]

**Comment by dmccreary** [comment]
The REST API can be easily setup and provides generic functions for working with documents, however it is not designed to be customized.   The URL patterns are fixed.

RXQ on the other hand is a framework for binding any REST URL to a function.  RXQ is tightly coupled with XQuery functions and you can specify the REST URL by changing a pattern expression.  RXQ is also simple to understand and easy to extend.

**Comment by RobertSzkutak** [comment]
"The REST API can be easily setup and provides generic functions for working with documents, however it is not designed to be customized. The URL patterns are fixed."

Not true. Editing rewriter.xml lets you define your own URL patterns in the same way as RXQ. https://docs.marklogic.com/guide/app-dev/XMLrewriter

To me personally, the benefit of RXQ has been a lighter learning curve and the ability to modify the rewriter to do things like perform consistent logging for all APIs.

**Comment by xquery** [comment]
yes and it would be possible to generate a native rewriter definition from annotations  as well.

Their usage does not have to be mutually exclusive, there is probably a sane way to integrate rxq usage within REST API.

**Comment by dmcassel** [comment]
Is RXQ used for two-tier apps? That would be a meaningful distinction.

**Comment by xquery** [comment]
yes it can be

**Comment by xquery** [comment]
note I have added an issue for enhancement to generate native rewriter (#49).

I added a few bullet points to README, but I would rather point to articles that provide opinions on why use RXQ ... closing this and will be on the lookout for Dan's article.

**Comment by dmcassel** [comment]
Clarifying: I wasn't asking about how rxq can be used with the REST API; rather, when would someone choose one versus the other. I think that would be a good addition to your FAQ. Some thoughts:

- RXQ
  - customizable functionality
  - good choice for a 2-tier environment
  - good choice to avoid providing default functionality that may cover too much ground
- REST API
  - covers search and document CRUD
  - well tested by MarkLogic
  - should be used in a 3-tier environment
